// sdk/examples/vue3/src/App.vue
<template>
  <div id="app">
    <nav class="navbar">
      <div class="nav-container">
        <h1>⚡ Vue 3 监控 SDK 测试</h1>
        <div class="nav-links">
          <router-link to="/">首页</router-link>
          <router-link to="/about">关于</router-link>
          <router-link to="/error-test">错误测试</router-link>
          <router-link to="/performance">性能测试</router-link>
        </div>
      </div>
    </nav>
    <main class="main-content">
      <router-view />
    </main>
  </div>
</template>

<script setup>
import { onMounted } from 'vue'

// Vue 3 Composition API
onMounted(() => {
  console.log('VITE_BASE:', import.meta.env.VITE_BASE)
})
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f5f5f5;
}

#app {
  min-height: 100vh;
}

.navbar {
  background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
  color: white;
  padding: 1rem 0;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.nav-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.nav-container h1 {
  font-size: 1.5rem;
}

.nav-links {
  display: flex;
  gap: 20px;
}

.nav-links a {
  color: white;
  text-decoration: none;
  padding: 8px 16px;
  border-radius: 4px;
  transition: background 0.3s;
}

.nav-links a:hover,
.nav-links a.router-link-active {
  background: rgba(255, 255, 255, 0.2);
}

.main-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}
</style>

// sdk/examples/svelte/src/App.svelte
<script>
  import { onMount } from 'svelte'
  import { Router, Route } from 'svelte-routing'
  import Home from './views/Home.svelte'
  import About from './views/About.svelte'
  import ErrorTest from './views/ErrorTest.svelte'
  import Performance from './views/Performance.svelte'
  import NavBar from './components/NavBar.svelte'
  
  // 从环境变量读取 base，默认为 '/'
  const base = import.meta.env.VITE_BASE || '/'
  
  onMount(() => {
    console.log('VITE_BASE:', import.meta.env.VITE_BASE)
  })
</script>

<Router url={base}>
  <div class="app">
    <NavBar />
    <main class="main-content">
      <Route path="/" component={Home} />
      <Route path="/about" component={About} />
      <Route path="/error-test" component={ErrorTest} />
      <Route path="/performance" component={Performance} />
    </main>
  </div>
</Router>

<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  :global(body) {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
      'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
      sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    background: #f5f5f5;
  }

  .app {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }


  .main-content {
    flex: 1;
    max-width: 1200px;
    width: 100%;
    margin: 0 auto;
    padding: 2rem;
  }
</style>
