// sdk/examples/vue3/src/App.vue
<template>
  <div id="app">
    <nav class="navbar">
      <div class="nav-container">
        <h1>⚡ Vue 3 监控 SDK 测试</h1>
        <div class="nav-links">
          <router-link to="/">首页</router-link>
          <router-link to="/about">关于</router-link>
          <router-link to="/error-test">错误测试</router-link>
          <router-link to="/performance">性能测试</router-link>
        </div>
      </div>
    </nav>
    <main class="main-content">
      <router-view />
    </main>
  </div>
</template>

<script setup>
import { onMounted } from 'vue'

// Vue 3 Composition API
onMounted(() => {
  console.log('VITE_BASE:', import.meta.env.VITE_BASE)
})
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f5f5f5;
}

#app {
  min-height: 100vh;
}

.navbar {
  background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
  color: white;
  padding: 1rem 0;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.nav-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.nav-container h1 {
  font-size: 1.5rem;
}

.nav-links {
  display: flex;
  gap: 20px;
}

.nav-links a {
  color: white;
  text-decoration: none;
  padding: 8px 16px;
  border-radius: 4px;
  transition: background 0.3s;
}

.nav-links a:hover,
.nav-links a.router-link-active {
  background: rgba(255, 255, 255, 0.2);
}

.main-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}
</style>

// sdk/examples/react/src/App.tsx
import { Routes, Route, Link, useLocation } from 'react-router-dom'
import { useEffect } from 'react'
import Home from './views/Home'
import About from './views/About'
import ErrorTest from './views/ErrorTest'
import Performance from './views/Performance'
import './App.css'

function App() {
  const location = useLocation()

  useEffect(() => {
    console.log('VITE_BASE:', import.meta.env.VITE_BASE)
  }, [])

  return (
    <div className="app">
      <nav className="navbar">
        <div className="nav-container">
          <h1 className="nav-title">React 监控 SDK 测试</h1>
          <div className="nav-links">
            <Link 
              to="/" 
              className={location.pathname === '/' ? 'active' : ''}
            >
              首页
            </Link>
            <Link 
              to="/about" 
              className={location.pathname === '/about' ? 'active' : ''}
            >
              关于
            </Link>
            <Link 
              to="/error-test" 
              className={location.pathname === '/error-test' ? 'active' : ''}
            >
              错误测试
            </Link>
            <Link 
              to="/performance" 
              className={location.pathname === '/performance' ? 'active' : ''}
            >
              性能测试
            </Link>
          </div>
        </div>
      </nav>

      <main className="main-content">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/about" element={<About />} />
          <Route path="/error-test" element={<ErrorTest />} />
          <Route path="/performance" element={<Performance />} />
        </Routes>
      </main>
    </div>
  )
}

export default App
